### ISSUE TITLE
Integrate new TermInfo queries into XMI

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB2#123]

**Comment by Robbie1977** [comment]
Processing step: https://github.com/VirtualFlyBrain/uk.ac.vfb.geppetto/blob/master/src/main/java/uk/ac/vfb/geppetto/VFBProcessTermInfo.java

**Comment by Robbie1977** [comment]
ecore docs: http://docs.geppetto.org/en/latest/geppettomodel.html?highlight=ecore

**Comment by Robbie1977** [comment]
Done
