### ISSUE TITLE
Bug with queries on Safari

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB2#138]
Selecting any query from TermInfo

=> "Select query for ..." e.g. 

<img width="673" alt="image" src="https://user-images.githubusercontent.com/112839/44007764-13a70f4a-9ed6-11e8-8ef9-befbf593ef4f.png">

i.e. query chosen is not selected - defaults to asking user to choose a query.  Then spins forever.  Choosing a query at this point does nothing.

The same bug happens on Safari on iOS.

Support info:
Referring page: https://v2.virtualflybrain.org/?i=VFB_00017894,VFB_00015994
System details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15 Size:[1435,505]

**Comment by dosumis** [comment]
Queries also fail to return if starting from query icon -> search -> choosing a query.

**Comment by Robbie1977** [comment]
Have finished pushing owlery changes should all be back to working order.

**Comment by dosumis** [comment]
Yep.  Now works.
