### ISSUE TITLE
DataSet descriptions - Change to KB requires patch to TermInfo rolling code

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB2#177]
##### Description of the problem

Minor schema change in KB (as of 141118)

DataSet.description: string -> list of strings
Site.description() string -> list of strings

I assume this will require a patch to the current TermInfo rolling code so that dataset descriptions are displayed properly in v2.

**Comment by dosumis** [comment]
Is this done?

**Comment by Robbie1977** [comment]
Both the new and old systems can handle description List<String> or String fine.
