### ISSUE TITLE
V2a search functionality is impaired

### ISSUE THREAD

**Issue by ah963** [VirtualFlyBrain/VFB2#192]
V2a searches and queries do not properly autocomplete and does not throw up best results first. Eg a search for mushroom body gives the first result as a paper and then painted domains on the L3 VNC
![Screen Shot 2019-04-02 at 09 47 48](https://user-images.githubusercontent.com/26765505/55389103-83d1d680-552c-11e9-9454-07bc847aec2f.png)

Search does not initially find GMR line, intersections or other images unless you first search for them by part entering a VFB id, then it seems to load all/most of them so they can be found in subsequent searches

**Comment by Robbie1977** [comment]
Fixed
