### ISSUE TITLE
Quick UX feedback

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/VFB2#193]
From my 15 minute session (looks great by the way!):

By far the biggest problem for me is reactivity; there should be a way to reduce resolution and make it super fast for older machines.. :P I know how hard this is. Here some details:

3D Viewer:
- (+)(-) buttons in 3D Viewer are too slow to be useful (compared to mousewheel scroll
- Minimising (_) the 3d viewer works, but then maximising it again
  - Takes too long (veeeeeery long)
  - Puts the 3D viewer underneath terminfo rather than into the main field
- If you decrease the size of TermInfo, the small menu on top of it (does this really belong on TermInfo?) does not change size gracefully (overlapping the rest of the TermInfo box for no reason):
![image](https://user-images.githubusercontent.com/7070631/62130955-0e0b2b00-b2d2-11e9-9532-7187a9bd8743.png)

TermInfo:
- Show all anatomy reloads the whole page and removes all my previous selections
- Is it useful that the lists "Related individuals" and "Relationships" are largely redundant (example "cluster 3.42 (VFB_00017691)"?
- Hitting the query "NBLAST potential GAL4's targetting Cha-F-000113" gives me a large table with almost no content, save some numbers.

**Comment by ddelpiano** [comment]
hi Nico, 
which browser did you use to test on your side? 

Thanks,
Dario

**Comment by matentzn** [comment]
Hey @ddelpiano! `Version 75.0.3770.142 (Official Build) (64-bit)`

**Comment by Robbie1977** [comment]
Reverted so no longer an issue.
