### ISSUE TITLE
Wrapping of labels on relationships is misleading.

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB2#198]
Wrapping on labels is misleading.

From this, it looks like ventrolateral neuropils is a neuromere: 
![image](https://user-images.githubusercontent.com/112839/62828384-09266f80-bc20-11e9-94ef-cefe8639e44f.png)

But this label actually applies to protocerebrum:
![image](https://user-images.githubusercontent.com/112839/62828394-4db20b00-bc20-11e9-9d3e-a788e18209ad.png)

Support info:
Sun Aug 11 2019 10:07:20 GMT 0900 (Japan Standard Time)
Chrome 76.0.3809.87 [1173,683]
https://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto?id=FBbt_00007059&i=VFB_00017894,VFB_00016138,VFB_00030627

```diff
- Warning: Failed prop type: There should be an equal number of

**Comment by dosumis** [comment]
**THIS IS NOT A BLOCKER FOR BETA RELEASE**

**Comment by Robbie1977** [comment]
Tried ```    display: grid``` but causes too many other issues when in a normal window may be easier to hide when the window gets this small.

**Comment by ddelpiano** [comment]
@Robbie1977 try to wrap the content of each <li></li> in a div like <li> <div> </div> </li> 
![Screenshot 2019-08-28 at 16 52 48](https://user-images.githubusercontent.com/37704177/63867027-76722880-c9b4-11e9-9acb-a9ed0e2e0464.png)
