### ISSUE TITLE
Colors missing from control panel / layers tool

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB2#199]
![image](https://user-images.githubusercontent.com/112839/62829546-05ecad00-bc3b-11e9-9be7-d3336a110715.png)

All appear white.

Should probably be considered a blocker for release?

Support info:
Sun Aug 11 2019 13:21:53 GMT 0900 (Japan Standard Time)
Chrome 76.0.3809.87 [1173,683]
https://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_00017894&i=VFB_00017894,VFB_00030627,VFB_00002347

```diff
- Warning: Failed prop type: There should be an equal number of

**Comment by tarelli** [comment]
Should be an easy fix @ddelpiano

**Comment by Robbie1977** [comment]
Fixed
