### ISSUE TITLE
autocomplete fail on query refinement

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB2#201]
Autocomplete working correctly (spotlight)
![image](https://user-images.githubusercontent.com/112839/63218698-2c5e9b00-c19b-11e9-910d-e5a65ed9d73b.png)

(exact match comes top)

Same search in query refinement:  

![image](https://user-images.githubusercontent.com/112839/63218706-49936980-c19b-11e9-9d22-cb73da9a2286.png)

(exact match no longer top - in fact - impossible to find because hit list is so long)

Support info:
Sun Aug 18 2019 09:29:20 GMT 0900 (Japan Standard Time)
Chrome 76.0.3809.87 [1309,702]
https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=FBbt_00111753&i=VFB_00017894,VFB_00030611

```diff
+ Passing instance: VFB_00030611_slices
+ Selection of ellipsoid body on adult brain template JFRC2
+ Selection of 3D Volume
+ Selection of ellipsoid body on adult brain template JFRC2
+ Selection of 3D Volume
+ Selection of ellipsoid body on adult brain template JFRC2
+ Selection of 3D Volume
+ Selection of ellipsoid body on adult brain template JFRC2
+ Selection of 3D Volume
+ Query requested: Compound Ref Query Expression found here neuron
```

**Comment by Robbie1977** [comment]
Repaired by fixing Geppetto-client code that was ignoring VFB custom configuration
