### ISSUE TITLE
Cluster searches broken/incomplete

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB2#203]
e.g. 
![image](https://user-images.githubusercontent.com/112839/63325821-7db68800-c35d-11e9-9173-6ba21a65233b.png)

Should be like VFB 1.5: 

- showing cluster image, exemplar etc

I guess I need to write a query -> JSON ?

Support info:
Tue Aug 20 2019 15:15:53 GMT 0800 (Taipei Standard Time)
Chrome 76.0.3809.87 [1073,681]
https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=FBbt_00003677&i=VFB_00017894,VFB_00030633,VFB_00004023

```diff
+ Passing instance: VFB_00004023_slices
+ Selection of Gad1-F-900045
+ Selection of 3D Skeleton
+ Selection of Gad1-F-900045
+ Selection of 3D Skeleton
+ Selection of Gad1-F-900045
+ Selection of 3D Skeleton
+ Selection of Gad1-F-900045
+ Selection of 3D Skeleton
+ Query requested: ImagesNeuronsClustered protocerebral bridge slice 9
```

**Comment by Robbie1977** [comment]
Fixed by repairing Cluster label in pdb
