### ISSUE TITLE
EP -> Anat query fail

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB2#204]
I thought this was fixed:

Expression found in Anat P{GMR50E04-GAL4} expression pattern

=> 
![image](https://user-images.githubusercontent.com/112839/64791475-b1a55780-d56f-11e9-99e5-27f0864236ea.png)

Support info:
Thu Sep 12 2019 15:09:30 GMT 0100 (British Summer Time)
Chrome 76.0.3809.87 [2327,1208]
https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFBexp_FBtp0060893&i=VFB_00017894,VFB_00021834

```diff
+ Selection of JRC_R50E04 GAL4 in the adult brain
+ Selection of 3D Volume
+ Selection of JRC_R50E04 GAL4 in the adult brain
+ Selection of 3D Volume
+ Selection of JRC_R50E04 GAL4 in the adult brain
+ Selection of 3D Volume
+ Selection of JRC_R50E04 GAL4 in the adult brain
+ Selection of 3D Volume
+ Query requested: Compound Ref Query Expression found in Anat P{GMR50E04-GAL4} expression pattern
+ Query requested: Compound Ref Query Expression found in Anat P{GMR50E04-GAL4} expression pattern
```

**Comment by Robbie1977** [comment]
JSON schema processing step had an issue with no results - this has been corrected
