### ISSUE TITLE
Odd thumbnail (found via searching for ORN 42a)

### ISSUE THREAD

**Issue by aoifelarkin** [VirtualFlyBrain/VFB2#209]
Interesting thumbnail for 
"" target="_blank">DoOR" cross-reference

Odd thumbnail (found via searching for ORN 42a)

Support info:
Tue Sep 17 2019 11:23:17 GMT 0100 (BST)
Safari 12.1.1 [1440,814]
https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=FBbt_00067042&i=VFB_00017894

```diff
+ PixiJS 4.8.8 - WebGL - http://www.pixijs.com/
+ Passing instance: VFB_00017894_slices
+ Selection of adult brain template JFRC2
+ Selection of 3D Volume
+ Selection of adult brain template JFRC2
+ Selection of 3D Volume
+ Selection of adult brain template JFRC2
+ Selection of 3D Volume
+ Selection of adult brain template JFRC2
+ Selection of 3D Volume
```

**Comment by Robbie1977** [comment]
@aoifelarkin The icon is correct. A fix is under testy for the broken link.
