### ISSUE TITLE
Focus term shouldn't be capitalised

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB2#213]
marta:  https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=FBbt_00007387&i=VFB_00017894
Should be vPN
![image](https://user-images.githubusercontent.com/4630768/65047344-39b5a380-d95a-11e9-9b8a-1941fbc98e23.png)

Support info:
Tue Sep 17 2019 14:47:24 GMT 0100 (British Summer Time)
Chrome 76.0.3809.132 [1920,1071]
https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=FBbt_00007387&i=VFB_00017894

```diff
+ Selection of adult brain template JFRC2
+ Selection of adult brain template JFRC2
+ Selection of adult brain template JFRC2
+ Selection of 3D Volume
+ Selection of adult brain template JFRC2
+ Selection of 3D Volume
+ Selection of adult brain template JFRC2
+ Selection of 3D Volume
+ Selection of adult brain template JFRC2
+ Selection of 3D Volume
```

**Comment by ddelpiano** [comment]
Addressed by https://github.com/VirtualFlyBrain/geppetto-vfb/pull/423
