### ISSUE TITLE
Reload triggered by selecting painted domain

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB2#217]
##### Description of the problem

Clicking on painted domain image frequently (but not always) => reload and loss of history.  I've seen this with multiple painted domains on JRC2 including Wedge and MB Calyx.  Sometimes this is repeatable after navigating back (with the browser) and trying again.  Sometimes not.

I've force reloaded so don't think this is down to cached client side code.

Log before reload:

```
Selection of 3D Skeleton
VM6289 react-dom.development.js:332 [Violation] 'click' handler took 181ms
[Violation] 'click' handler took 275ms
VM6389 Manager.js:109 Adding variable: 1.277099609375ms
VM6521 VFBMain.js_+_19_modules:4238 Selection of Gad1-F-200073
VM6521 VFBMain.js_+_19_modules:4238 Selection of 3D Skeleton  
```

Click on painted domain -> Reload.

Log during/after reload.

```
Navigated to https://v2.virtualflybrain.org/org.geppetto.frontend/org.geppetto.frontend
VM8965 react-dom.development.js:25195 Download the React DevTools for a better development experience: https://fb.me/react-devtools
```

See below for full log 
##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

Selection of 3D Skeleton
VM6289 react-dom.development.js:332 [Violation] 'click' handler took 181ms
[Violation] 'click' handler took 275ms
VM6389 Manager.js:109 Adding variable: 1.277099609375ms
VM6521 VFBMain.js_+_19_modules:4238 Selection of Gad1-F-200073
VM6521 VFBMain.js_+_19_modules:4238 Selection of 3D Skeleton
Navigated to https://v2.virtualflybrain.org/org.geppetto.frontend/org.geppetto.frontend
react-dom.development.js:25195 Download the React DevTools for a better development experience: https://fb.me/react-devtools
react-dom.development.js:11494 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: BrowserRouter, Redirect, Router, Switch
printWarning @ react-dom.development.js:11494
lowPriorityWarning @ react-dom.development.js:11513
ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11674
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23134
commitRootImpl @ react-dom.development.js:22428
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
commitRoot @ react-dom.development.js:22414
scheduleUpdateOnFiber @ react-dom.development.js:21421
scheduleRootUpdate @ react-dom.development.js:24319
updateContainerAtExpirationTime @ react-dom.development.js:24347
updateContainer @ react-dom.development.js:24436
(anonymous) @ react-dom.development.js:24963
unbatchedUpdates @ react-dom.development.js:21687
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24962
render @ react-dom.development.js:25042
(anonymous) @ Main.js:22
mightThrow @ jquery.js:3557
process @ jquery.js:3625
setTimeout (async)
(anonymous) @ jquery.js:3663
fire @ jquery.js:3291
fireWith @ jquery.js:3421
fire @ jquery.js:3429
fire @ jquery.js:3291
fireWith @ jquery.js:3421
ready @ jquery.js:3901
completed @ jquery.js:3911
react-dom.development.js:11494 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Router, Switch
printWarning @ react-dom.development.js:11494
lowPriorityWarning @ react-dom.development.js:11513
ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11680
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23134
commitRootImpl @ react-dom.development.js:22428
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
commitRoot @ react-dom.development.js:22414
scheduleUpdateOnFiber @ react-dom.development.js:21421
scheduleRootUpdate @ react-dom.development.js:24319
updateContainerAtExpirationTime @ react-dom.development.js:24347
updateContainer @ react-dom.development.js:24436
(anonymous) @ react-dom.development.js:24963
unbatchedUpdates @ react-dom.development.js:21687
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24962
render @ react-dom.development.js:25042
(anonymous) @ Main.js:22
mightThrow @ jquery.js:3557
process @ jquery.js:3625
setTimeout (async)
(anonymous) @ jquery.js:3663
fire @ jquery.js:3291
fireWith @ jquery.js:3421
fire @ jquery.js:3429
fire @ jquery.js:3291
fireWith @ jquery.js:3421
ready @ jquery.js:3901
completed @ jquery.js:3911
react-dom.development.js:11494 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Component, ControlPanel, GridTitle, Griddle, QueryBuilder, Route, VFBMain, VFBToolBar
printWarning @ react-dom.development.js:11494
lowPriorityWarning @ react-dom.development.js:11513
ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11674
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23134
commitRootImpl @ react-dom.development.js:22428
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
commitRoot @ react-dom.development.js:22414
runRootCallback @ react-dom.development.js:21554
(anonymous) @ react-dom.development.js:11353
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushSyncCallbackQueueImpl @ react-dom.development.js:11349
flushSyncCallbackQueue @ react-dom.development.js:11338
unbatchedUpdates @ react-dom.development.js:21692
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24962
render @ react-dom.development.js:25042
(anonymous) @ Main.js:22
mightThrow @ jquery.js:3557
process @ jquery.js:3625
setTimeout (async)
(anonymous) @ jquery.js:3663
fire @ jquery.js:3291
fireWith @ jquery.js:3421
fire @ jquery.js:3429
fire @ jquery.js:3291
fireWith @ jquery.js:3421
ready @ jquery.js:3901
completed @ jquery.js:3911
react-dom.development.js:11494 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Griddle, Layout, MenuSection, Rnd, Route, Tab, TabSet
printWarning @ react-dom.development.js:11494
lowPriorityWarning @ react-dom.development.js:11513
ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11680
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23134
commitRootImpl @ react-dom.development.js:22428
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
commitRoot @ react-dom.development.js:22414
runRootCallback @ react-dom.development.js:21554
(anonymous) @ react-dom.development.js:11353
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushSyncCallbackQueueImpl @ react-dom.development.js:11349
flushSyncCallbackQueue @ react-dom.development.js:11338
unbatchedUpdates @ react-dom.development.js:21692
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24962
render @ react-dom.development.js:25042
(anonymous) @ Main.js:22
mightThrow @ jquery.js:3557
process @ jquery.js:3625
setTimeout (async)
(anonymous) @ jquery.js:3663
fire @ jquery.js:3291
fireWith @ jquery.js:3421
fire @ jquery.js:3429
fire @ jquery.js:3291
fireWith @ jquery.js:3421
ready @ jquery.js:3901
completed @ jquery.js:3911
three.module.js:21297 THREE.WebGLRenderer 87
12[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
VFBMain.js_+_19_modules:4141 Loading default Adult Brain VFB_00017894 template.
react-dom.development.js:332 [Violation] 'setTimeout' handler took 95ms
react-dom.development.js:11494 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Component, Draggable, Resizable, StackViewer
printWarning @ react-dom.development.js:11494
lowPriorityWarning @ react-dom.development.js:11513
ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11680
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23134
commitRootImpl @ react-dom.development.js:22428
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
commitRoot @ react-dom.development.js:22414
runRootCallback @ react-dom.development.js:21554
(anonymous) @ react-dom.development.js:11353
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushSyncCallbackQueueImpl @ react-dom.development.js:11349
flushSyncCallbackQueue @ react-dom.development.js:11338
unbatchedUpdates @ react-dom.development.js:21692
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24962
render @ react-dom.development.js:25042
(anonymous) @ Main.js:22
mightThrow @ jquery.js:3557
process @ jquery.js:3625
setTimeout (async)
(anonymous) @ jquery.js:3663
fire @ jquery.js:3291
fireWith @ jquery.js:3421
fire @ jquery.js:3429
fire @ jquery.js:3291
fireWith @ jquery.js:3421
ready @ jquery.js:3901
completed @ jquery.js:3911
jquery.js:3623 [Violation] 'setTimeout' handler took 866ms
VFBMain.js_+_19_modules:4238 Host for MessageSocket to connect: wss://v2.virtualflybrain.org/org.geppetto.frontend/GeppettoServlet
Manager.js:55 Parsing model: 1.46484375ms
Manager.js:60 Creating model: 13.270751953125ms
Manager.js:66 Creating instances: 2.343017578125ms
Manager.js:71 Loading Project: 605.3349609375ms
Manager.js:292 Loading Experiment: 2.001220703125ms
Manager.js:109 Adding variable: 3.822021484375ms
/org.geppetto.frontend/geppetto:1 The connection used to load resources from https://flweb.janelia.org used TLS 1.0 or TLS 1.1, which are deprecated and will be disabled in the future. Once disabled, users will be prevented from loading these resources. The server should enable TLS 1.2 or later. See https://www.chromestatus.com/feature/5654791610957824 for more information.
react-dom.development.js:11494 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: HTMLViewer
printWarning @ react-dom.development.js:11494
lowPriorityWarning @ react-dom.development.js:11513
ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11680
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23134
commitRootImpl @ react-dom.development.js:22428
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
commitRoot @ react-dom.development.js:22414
runRootCallback @ react-dom.development.js:21554
(anonymous) @ react-dom.development.js:11353
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushSyncCallbackQueueImpl @ react-dom.development.js:11349
flushSyncCallbackQueue @ react-dom.development.js:11338
scheduleUpdateOnFiber @ react-dom.development.js:21431
enqueueSetState @ react-dom.development.js:13100
Component.setState @ react.development.js:325
setData @ VFBTermInfo.js:117
setTermInfo @ VFBTermInfo.js:690
handleSceneAndTermInfoCallback @ VFBMain.js_+_19_modules:3350
(anonymous) @ VFBMain.js_+_19_modules:3314
parseAndNotify @ MessageSocket.js:213
processBinaryMessage @ MessageSocket.js:230
GEPPETTO.MessageSocket.socket.onmessage @ MessageSocket.js:60
/org.geppetto.frontend/geppetto:1 Mixed Content: The page at 'https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto' was loaded over HTTPS, but requested an insecure image 'http://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc-sa.png'. This content should also be served over HTTPS.
react-dom.development.js:11494 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: GridRowContainer
printWarning @ react-dom.development.js:11494
lowPriorityWarning @ react-dom.development.js:11513
ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11680
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23134
commitRootImpl @ react-dom.development.js:22428
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
commitRoot @ react-dom.development.js:22414
runRootCallback @ react-dom.development.js:21554
(anonymous) @ react-dom.development.js:11353
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushSyncCallbackQueueImpl @ react-dom.development.js:11349
flushSyncCallbackQueue @ react-dom.development.js:11338
scheduleUpdateOnFiber @ react-dom.development.js:21431
enqueueSetState @ react-dom.development.js:13100
Component.setState @ react.development.js:325
addData @ controlpanel.js:1537
handleAddData @ controlpanel.js:1978
triggerEvents @ backbone.js:328
triggerApi @ backbone.js:315
eventsApi @ backbone.js:103
Events.trigger @ backbone.js:305
swapResolvedType @ Manager.js:149
messageHandler.<computed> @ MessageHandler.js:123
onMessage @ MessageHandler.js:253
parseAndNotify @ MessageSocket.js:206
processBinaryMessage @ MessageSocket.js:230
GEPPETTO.MessageSocket.socket.onmessage @ MessageSocket.js:60
OBJLoader.js:579 OBJLoader: 1463.94580078125ms
VFBMain.js_+_19_modules:4238 Adding adult brain template JFRC2 to 0
VFBMain.js_+_19_modules:4238 Passing 1 instances
react-dom.development.js:11494 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Component
printWarning @ react-dom.development.js:11494
lowPriorityWarning @ react-dom.development.js:11513
ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11680
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23134
commitRootImpl @ react-dom.development.js:22428
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
commitRoot @ react-dom.development.js:22414
runRootCallback @ react-dom.development.js:21554
(anonymous) @ react-dom.development.js:11353
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushSyncCallbackQueueImpl @ react-dom.development.js:11349
flushSyncCallbackQueue @ react-dom.development.js:11338
scheduleUpdateOnFiber @ react-dom.development.js:21431
enqueueSetState @ react-dom.development.js:13100
Component.setState @ react.development.js:325
addSlices @ VFBMain.js_+_19_modules:2758
(anonymous) @ VFBMain.js_+_19_modules:2849
(anonymous) @ VFBMain.js_+_19_modules:2847
(anonymous) @ VFBMain.js_+_19_modules:2846
triggerEvents @ backbone.js:328
triggerApi @ backbone.js:315
eventsApi @ backbone.js:103
Events.trigger @ backbone.js:305
swapResolvedType @ Manager.js:149
messageHandler.<computed> @ MessageHandler.js:123
onMessage @ MessageHandler.js:253
parseAndNotify @ MessageSocket.js:206
processBinaryMessage @ MessageSocket.js:230
GEPPETTO.MessageSocket.socket.onmessage @ MessageSocket.js:60
VFBMain.js_+_19_modules:4238 Loading....
VFBMain.js_+_19_modules:4238 
    PixiJS 4.8.8 - ✰ WebGL ✰      http://www.pixijs.com/    ♥♥♥ 
deprecation.js:32 Deprecation Warning: text style property 'font' is now deprecated, please use the 'fontFamily','fontSize',fontStyle','fontVariant' and 'fontWeight' properties from now on
VFBMain.js_+_19_modules:4238 Passing instance: VFB_00017894_slices
Manager.js:150 An import type has been resolved to a full type and swapped into the Geppetto model: 1646.47412109375ms
VFBMain.js_+_19_modules:4238 Selection of adult brain template JFRC2
VFBMain.js_+_19_modules:4238 Selection of 3D Volume
VFBMain.js_+_19_modules:4238 Selection of adult brain template JFRC2
VFBMain.js_+_19_modules:4238 Selection of 3D Volume
VFBMain.js_+_19_modules:4238 Selection of adult brain template JFRC2
VFBMain.js_+_19_modules:4238 Selection of 3D Volume
MessageSocket.js:51 [Violation] 'message' handler took 1965ms
BaseTexture.js:795 BaseTexture added to the cache with an id [https://www.virtualflybrain.org/fcgi/wlziipsrv.fcgi?wlz=/disk/data/VFB/IMAGE_DATA/VFB/i/0001/7894/volume.wlz&sel=0,255,255,255&mod=zeta&fxp=511,255,108&scl=1.0&dst=0.0&pit=0&yaw=0&rol=0&qlt=80&jtl=0] that already had an entry
addToCache @ BaseTexture.js:795
fromLoader @ Texture.js:482
textureParser @ textureParser.js:9
(anonymous) @ Loader.js:676
(anonymous) @ async.js:45
setTimeout (async)
next @ async.js:44
blobMiddleware @ blob.js:69
(anonymous) @ Loader.js:676
(anonymous) @ async.js:45
setTimeout (async)
next @ async.js:44
eachSeries @ async.js:50
_onLoad @ Loader.js:675
dispatch @ mini-signals.js:93
_finish @ Resource.js:552
complete @ Resource.js:371
load (async)
_loadElement @ Resource.js:582
load @ Resource.js:453
(anonymous) @ Loader.js:626
next @ async.js:37
eachSeries @ async.js:50
_loadResource @ Loader.js:615
Loader._boundLoadResource @ Loader.js:132
process @ async.js:128
resume @ async.js:157
load @ Loader.js:546
updateImages @ StackViewerComponent.js:1019
checkStack @ StackViewerComponent.js:692
componentDidUpdate @ StackViewerComponent.js:116
commitLifeCycles @ react-dom.development.js:20064
commitLayoutEffects @ react-dom.development.js:22813
callCallback @ react-dom.development.js:347
invokeGuardedCallbackDev @ react-dom.development.js:397
invokeGuardedCallback @ react-dom.development.js:454
commitRootImpl @ react-dom.development.js:22585
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
commitRoot @ react-dom.development.js:22414
runRootCallback @ react-dom.development.js:21554
(anonymous) @ react-dom.development.js:11353
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushSyncCallbackQueueImpl @ react-dom.development.js:11349
flushSyncCallbackQueue @ react-dom.development.js:11338
scheduleUpdateOnFiber @ react-dom.development.js:21431
enqueueSetState @ react-dom.development.js:13100
Component.setState @ react.development.js:325
(anonymous) @ VFBMain.js_+_19_modules:2854
(anonymous) @ VFBMain.js_+_19_modules:2847
(anonymous) @ VFBMain.js_+_19_modules:2846
triggerEvents @ backbone.js:328
triggerApi @ backbone.js:315
eventsApi @ backbone.js:103
Events.trigger @ backbone.js:305
swapResolvedType @ Manager.js:149
messageHandler.<computed> @ MessageHandler.js:123
onMessage @ MessageHandler.js:253
parseAndNotify @ MessageSocket.js:206
processBinaryMessage @ MessageSocket.js:230
GEPPETTO.MessageSocket.socket.onmessage @ MessageSocket.js:60
Show 29 more frames
Texture.js:512 Texture added to the cache with an id [https://www.virtualflybrain.org/fcgi/wlziipsrv.fcgi?wlz=/disk/data/VFB/IMAGE_DATA/VFB/i/0001/7894/volume.wlz&sel=0,255,255,255&mod=zeta&fxp=511,255,108&scl=1.0&dst=0.0&pit=0&yaw=0&rol=0&qlt=80&jtl=0] that already had an entry
addToCache @ Texture.js:512
fromLoader @ Texture.js:483
textureParser @ textureParser.js:9
(anonymous) @ Loader.js:676
(anonymous) @ async.js:45
setTimeout (async)
next @ async.js:44
blobMiddleware @ blob.js:69
(anonymous) @ Loader.js:676
(anonymous) @ async.js:45
setTimeout (async)
next @ async.js:44
eachSeries @ async.js:50
_onLoad @ Loader.js:675
dispatch @ mini-signals.js:93
_finish @ Resource.js:552
complete @ Resource.js:371
load (async)
_loadElement @ Resource.js:582
load @ Resource.js:453
(anonymous) @ Loader.js:626
next @ async.js:37
eachSeries @ async.js:50
_loadResource @ Loader.js:615
Loader._boundLoadResource @ Loader.js:132
process @ async.js:128
resume @ async.js:157
load @ Loader.js:546
updateImages @ StackViewerComponent.js:1019
checkStack @ StackViewerComponent.js:692
componentDidUpdate @ StackViewerComponent.js:116
commitLifeCycles @ react-dom.development.js:20064
commitLayoutEffects @ react-dom.development.js:22813
callCallback @ react-dom.development.js:347
invokeGuardedCallbackDev @ react-dom.development.js:397
invokeGuardedCallback @ react-dom.development.js:454
commitRootImpl @ react-dom.development.js:22585
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
commitRoot @ react-dom.development.js:22414
runRootCallback @ react-dom.development.js:21554
(anonymous) @ react-dom.development.js:11353
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushSyncCallbackQueueImpl @ react-dom.development.js:11349
flushSyncCallbackQueue @ react-dom.development.js:11338
scheduleUpdateOnFiber @ react-dom.development.js:21431
enqueueSetState @ react-dom.development.js:13100
Component.setState @ react.development.js:325
(anonymous) @ VFBMain.js_+_19_modules:2854
(anonymous) @ VFBMain.js_+_19_modules:2847
(anonymous) @ VFBMain.js_+_19_modules:2846
triggerEvents @ backbone.js:328
triggerApi @ backbone.js:315
eventsApi @ backbone.js:103
Events.trigger @ backbone.js:305
swapResolvedType @ Manager.js:149
messageHandler.<computed> @ MessageHandler.js:123
onMessage @ MessageHandler.js:253
parseAndNotify @ MessageSocket.js:206
processBinaryMessage @ MessageSocket.js:230
GEPPETTO.MessageSocket.socket.onmessage @ MessageSocket.js:60
Show 29 more frames

**Comment by ddelpiano** [comment]
This should be solved now with the latest fixes:
https://github.com/VirtualFlyBrain/geppetto-vfb/pull/413
https://github.com/VirtualFlyBrain/geppetto-vfb/pull/421

Closing.
