### ISSUE TITLE
Slow&delayed response in 3D viewer

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB2#22]
I find that on moving or rotating the template (only, nothing else displayed), there is a significant lag between clicking and moving the mouse, and the template starting to move.
The movement of the template is also much decreased relative to the movement of the mouse, so that I have to move the mouse quite a lot to get a small movement of the template.

It would be better if the template movement mirrored the mouse movement better.

Chrome Version 64.0.3282.167

(Reassign if needed)

**Comment by Robbie1977** [comment]
Will add to improvements in 3D manipulation in general. Moving selection away from mouse down (trying to select whilst dragging) should speed up initialisation of drag.

**Comment by Robbie1977** [comment]
This was a setting that I speeded up after Matteo had slowed down.
