### ISSUE TITLE
adult cerebral ganglion on adult brain template JFRC2 (VFB_00030849) displaying incorrectly in 3D view

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB2#229]
adult cerebral ganglion on adult brain template JFRC2 (VFB_00030849) loads correctly in the slice viewer, but the domains in the 3D view are only a subset of the cerebral ganglion domains. (tested on v2 and v2-dev)

![Screenshot 2020-05-19 at 08 27 30](https://user-images.githubusercontent.com/56207505/82297461-9adebc80-99aa-11ea-982d-419a0693336d.png)

Support info:
Tue May 19 2020 08:26:48 GMT 0100 (British Summer Time)
Chrome 81.0.4044.138 [1402,754]
https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_00030849&i=VFB_00017894,VFB_00030849

```diff
+ Adding 8 instances to 705
+ Passing 711 instances
+ Adding 8 instances to 711
+ Passing 717 instances
+ Adding 8 instances to 717
+ Passing 723 instances
+ Adding 8 instances to 723
+ Passing 729 instances
+ Adding 8 instances to 729
+ Passing 735 instances
```

**Comment by Robbie1977** [comment]
Resolved
