### ISSUE TITLE
Deselecting everything is not intuitive

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB2#230]
Intuitively, clicking on a blank region of the 3D viewer or the slice viewer should deselect everything (not tested). Currently it's not obvious a user should use the hand icon to deselect.

Support info:
Tue May 19 2020 09:00:57 GMT 0100 (British Summer Time)
Chrome 81.0.4044.138 [1402,754]
https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_00017894&i=VFB_00017894,VFB_00069565,VFB_00069337,VFB_00030875

```diff
+ Passing 5 instances
+ Passing instance: VFB_00030875_slices
+ Query requested: lineageClonesIn lobe system of adult mushroom body
+ Index not listed: 31
+ Index not listed: 101
+ Index not listed: 109
+ Index not listed: 115
+ Index not listed: 25
+ Index not listed: 101
+ Index not listed: 107
```

**Comment by ddelpiano** [comment]
Assigned this back to you guys to discuss over the wanted behaviour that we need to implement.

**Comment by admclachlan** [comment]
can rethink this for vfb3
