### ISSUE TITLE
Firefox: scroll bar covers the selection tickboxes in query results

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB2#231]
It's difficult to use the tickboxes in firefox because of this.

<img width="1207" alt="Screenshot 2020-05-19 at 09 25 49" src="https://user-images.githubusercontent.com/56207505/82303560-00cf4200-99b3-11ea-9bfc-0579bba4fa55.png">

Support info:
Tue May 19 2020 09:26:18 GMT 0100 (British Summer Time)
Firefox 76.0 [1341,705]
https://v2-dev.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_00030901&i=VFB_00017894,VFB_00030901

```diff
+ Adding 2 instances to 3
+ Adding 2 instances to 3
+ Adding 2 instances to 3
+ Adding 2 instances to 3
+ Adding 2 instances to 3
+ Adding 2 instances to 3
+ Adding 2 instances to 3
+ Adding 2 instances to 3
+ Adding 2 instances to 3
+ Adding 2 instances to 3
```

**Comment by Robbie1977** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=764076

**Comment by Robbie1977** [comment]
https://stackoverflow.com/questions/47138603/scroll-issue-on-firefox-vs-webkit-browsers-side-navigation-text-truncate-and

**Comment by Robbie1977** [comment]
fixed!
