### ISSUE TITLE
No opacity slider in colour selection?

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB2#232]
I'm not seeing an option to adjust opacity in either of the layers or term info colour selection tools.  This would mostly be useful for templates and domains so that their colours do not interfere too much with the neurons and expression patterns shown within these volumes. Might also be nice to have the colour selection tools always be the same to make things easier for the user.

**Comment by ddelpiano** [comment]
https://casesandberg.github.io/react-color/

As discussed at the sprint call this is the library we use at the moment, feel free to choose another picker and we can swap that in VFB.
Thx!

**Comment by admclachlan** [comment]
I would vote for the chrome colour picker, maybe without the hex colour code section if possible, as it's simliar to what's already there but with the opacity slider.
