### ISSUE TITLE
Domains of adult brain template JFRC2 inconsistent naming

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB2#233]
The majority of the JFRC2 domains follow the format 'X on adult brain template JFRC2'. However, 'SIP - painted domain JFRC2' and 'PB - painted domain JFRC2' are not presented in this format. This could potentially cause an issue as searching for 'superior lateral protocerebrum on adult brain template JFRC2' or 'superior medial protocerebrum on adult brain template JFRC2' works, but 'superior intermediate protocerebrum on adult brain template JFRC2' does not.

Support info:
Wed May 20 2020 10:10:55 GMT 0100 (British Summer Time)
Chrome 81.0.4044.138 [1402,754]
http://v2-dev2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_00030628&i=VFB_00017894,VFB_00030621,VFB_00030622,VFB_00030609,VFB_00030625,VFB_00030619,VFB_00030900,VFB_00030605,VFB_00030600,VFB_00030602,VFB_00030613,VFB_00030617,VFB_00030616,VFB_00030631,VFB_00030615,VFB_00030606,VFB_00030901,VFB_00030902,VFB_00030903,VFB_00030620,VFB_00030612,VFB_00030611,VFB_00030629,VFB_00030624,VFB_00030633,VFB_00030623,VFB_00030628,VFB_00030614,VFB_00030608,VFB_00030632,VFB_00030626,VFB_00030630,VFB_00030627,VFB_00030610,VFB_00030838,VFB_00030601,VFB_00030603,VFB_00030618,VFB_00030599,VFB_00030840,VFB_00030604,VFB_00030607

```diff
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
```

**Comment by Clare72** [comment]
done
