### ISSUE TITLE
Truman Larval Flip-Out Collection is listed twice in 'List all datasets aligned to L3 CNS template - Wood2018' query

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB2#234]
Listed once with 'unlicensed' and once with 'CC-BY-SA_4.0'. Data itself does not appear to be duplicated, and the dataset only appears once when directly searched for.

<img width="778" alt="Screenshot 2020-05-20 at 12 01 09" src="https://user-images.githubusercontent.com/56207505/82439080-fe8fe500-9a91-11ea-822c-22b90cdad3f6.png">

Support info:
Wed May 20 2020 12:01:21 GMT 0100 (British Summer Time)
Chrome 81.0.4044.138 [857,714]
http://v2-dev2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_00049000&i=VFB_00049000

```diff
+ Adding L3 CNS template - Wood2018 to 1
+ Passing instance: VFB_00049000_slices
+ Buffered 18000 tiles
+ Query requested: alignedDatasets L3 CNS template - Wood2018
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
```

**Comment by dosumis** [comment]
This  is  an  artefact of  the current  pipeline.   It will be  fixed when we switch to the new (v2) pipeline in the summer.  I'm not sure it's worth the effort to find a  way to fix before then.
