### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB2#235]
'Tell us about your paper' section contains 'datayour'.

'Help us improve the site' section contains 'project,you' and 'inthe'.

Support info:
Tue May 26 2020 08:16:41 GMT 0100 (British Summer Time)
Chrome 81.0.4044.138 [1381,756]
http://v2-dev2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_00017894&i=VFB_00017894

```diff
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
```

**Comment by Robbie1977** [comment]
missing spaces added
