### ISSUE TITLE
adult brain template ito2014 and L1 larval CNS ssTEM templates default to wireframe

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB2#236]
Inconsistent with other templates.

Support info:
Wed May 27 2020 10:37:49 GMT 0100 (British Summer Time)
Chrome 81.0.4044.138 [1381,756]
http://v2-dev2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_00030786&i=VFB_00030786

```diff
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
```

**Comment by Robbie1977** [comment]
This was an old choice to avoid issues with visibility on these particular templates but since the volume material has been improved so I'll remove the wireframe defaults on these templates

**Comment by Robbie1977** [comment]
Fixed in https://github.com/VirtualFlyBrain/geppetto-vfb/commit/dddec578cca3c8557115bed1f1dc9815ec01e0b2
