### ISSUE TITLE
Test Server: Newly loaded volumes appear to reduce performance until they are hidden and unhidden

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB2#238]
Especially apparent with loading the 'JRC2018Unisex' template. Tested in Chrome and Firefox on mac. The poor performance affects other browser tabs. Doesn't seem to be server issue as the volumes load in fine and waiting doesn't help, only hiding/unhiding fixes it. Does not happen on the live server.

Here is the JFRC2 template on the test server when opened and not interacted with for a few minutes, GPU usage is very high:

![Screenshot 2020-06-02 at 10 07 06](https://user-images.githubusercontent.com/56207505/83501980-d7390f00-a4b8-11ea-8c4f-78d74b0ba93a.png)

After hide/unhide (and using the camera button in the 3d view to keep it spinning), GPU usage slowly drops:

![Screenshot 2020-06-02 at 10 11 26](https://user-images.githubusercontent.com/56207505/83502404-6e05cb80-a4b9-11ea-88d1-13d7f4165413.png)

And on win10 with dedicated GPU:

![Capture](https://user-images.githubusercontent.com/56207505/83504384-58de6c00-a4bc-11ea-86b9-54fd6ddca4df.PNG)

Support info:
Fri May 29 2020 10:53:31 GMT 0100 (British Summer Time)
Chrome 81.0.4044.138 [1381,756]
https://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_00101567&i=VFB_00101567

```diff
+ Buffered 18000 tiles
+ Passing instance: VFB_00101567_slices
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18277 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
```

**Comment by Robbie1977** [comment]
@admclachlan When you get time can you retest with the latest to see if latest meshes have improved the situation.

**Comment by admclachlan** [comment]
This is on V2a right? It seems to have helped so that on my win10 machine with dedicated GPU there is no perceptible slowdown and my mbp feels more responsive when the volumes first load in. I'm still seeing high (100% on mbp, 40% on win10) GPU useage when volumes first load though, which drops to almost nothing on win10 and <10% on the mbp after about 30sec-1min (although sometime interaction with the 3d viewer is required), at which point the 3d viewer becomes much more responsive on the mbp. GPU useage remains lower even when using the spinning view. This also happens with anything else loaded in to the 3d viewer like neuron skeletons, so when someone is actually using the site to load multiple things into the 3d viewer the high GPU use is pretty much constant. It makes my mbp hot and causes high battery drain. Focus also has no effect during the high GPU use period, but does after it stops.
