### ISSUE TITLE
Test Server: Selecting multiple images from query results is very slow

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB2#239]
Might be related to the load order. If you have a query with multiple results and want to load multiple images, using the tick boxes is very slow as the images start loading in as you select them. It would be much faster if you could select all the images from the query results and then load them, even if you had to wait after they are all selected.

Support info:
Fri May 29 2020 11:01:24 GMT 0100 (British Summer Time)
Chrome 81.0.4044.138 [1381,756]
https://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_00101567&i=VFB_00101567,VFB_00102275

```diff
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
```

**Comment by Robbie1977** [comment]
@ddelpiano The loading spinner (on the tickbox) has disappeared at some point?
