### ISSUE TITLE
No tree for JRC2018u template on v2a

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB2#244]
![image](https://user-images.githubusercontent.com/112839/83664943-9decc600-a5c2-11ea-89cc-e140dc279a6a.png)

or hemibrain
![image](https://user-images.githubusercontent.com/112839/83665142-ef955080-a5c2-11ea-8ebb-3aecfc0d2cc4.png)

Support info:
Wed Jun 03 2020 17:49:39 GMT 0100 (British Summer Time)
Chrome 83.0.4103.61 [1215,624]
https://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_00101567&i=VFB_00101567

```diff
+ Buffered 18000 tiles
+ Buffered 18277 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
+ Buffered 18000 tiles
```

**Comment by Robbie1977** [comment]
My bad; was pointing at pdb which doesn't have the new templates yet. I'll switch back on release
