### ISSUE TITLE
Caps lost in name and definitions in query

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB2#27]
![caps_issue](https://user-images.githubusercontent.com/1872083/36907346-5409aa6a-1e30-11e8-9af1-32923e1250cb.png)
Query for adult antennal lobe. From there choose

'Query for: Neurons with synaptic terminals in adult antennal lobe'
Caps lost: 
Name: 'adult antennal lobe projection neuron adpn' should be 'adult antennal lobe projection neuron adPN'

Definition:'An adult antennal lobe projection neuron that is derived from neuroblast alad1 (fbbt:00067346). all of these neurons have axons that fasciculate with the medial antennal lobe tract (malt) and innervate the lateral horn' should be 'An adult antennal lobe projection neuron that is derived from neuroblast ALad1 (FBbt:00067346). All of these neurons have axons that fasciculate with the medial antennal lobe tract (mALT) and innervate the lateral horn.

See screenshot for other examples.

**Comment by Robbie1977** [comment]
Caused by reinstated capitalisation with new less formatting:  https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/components/interface/query/query.less#L457

**Comment by Robbie1977** [comment]
Still name being lowercased - need to track down code (not CSS)

**Comment by Robbie1977** [comment]
CSS change fixed for definitions but not names

**Comment by Robbie1977** [comment]
Still an issue for ```name``` and ```definition``` columns

**Comment by Robbie1977** [comment]
Issue moved to [VirtualFlyBrain/geppetto-vfb #191](https://github.com/VirtualFlyBrain/geppetto-vfb/issues/191) via [**ZenHub**](https://www.zenhub.com/)
