### ISSUE TITLE
Images cleared through the clear all button are not removed from the layers panel

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB2#279]
The images are removed from the 3d view and are greyed out in the layers panel, but not removed. Images must be individually deleted manually.

%0A%0A%0A%0A%0A%0ASupport%20info%3A%0AWed Nov 04 2020 10:45:28 GMT+0000 (Greenwich Mean Time)%0AChrome%2086.0.4240.111%20%5B2443,1498%5D%0Ahttp://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_00102281%26i=VFB_00101567,VFB_00102282,VFB_00102281%0A%0A%60%60%60diff%0A%2B Instance passed to handlerInstanceUpdate is undefined%0A%2B Instance passed to handlerInstanceUpdate is undefined%0A%2B Instance passed to handlerInstanceUpdate is undefined%0A%2B Instance passed to handlerInstanceUpdate is undefined%0A%2B Instance passed to handlerInstanceUpdate is undefined%0A%2B Instance passed to handlerInstanceUpdate is undefined%0A%2B Instance passed to handlerInstanceUpdate is undefined%0A%2B Instance passed to handlerInstanceUpdate is undefined%0A%2B Instance passed to handlerInstanceUpdate is undefined%0A%2B Instance passed to handlerInstanceUpdate is undefined%0A%2B Query requested: PaintedDomains JRC2018Unisex%0A%2B Instance passed to handlerInstanceUpdate is undefined%0A%2B Instance passed to handlerInstanceUpdate is undefined%0A%2B Query requested: AllAlignedImages JRC2018Unisex%0A%2B Query requested: PaintedDomains JRC2018Unisex%0A%2B Instance passed to handlerInstanceUpdate is undefined%0A%2B Instance passed to handlerInstanceUpdate is undefined%0A%60%60%60%0A

**Comment by Robbie1977** [comment]
on 'clear All' greyed out values are left:

![image](https://user-images.githubusercontent.com/4630768/99246668-9e3dee00-27fd-11eb-8b8e-30edab47fa1e.png)

**Comment by admclachlan** [comment]
Appears to be fixed, close?
