### ISSUE TITLE
Sort order problems with autocomplete

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB2#286]
The order of terms in a query should not matter, except in the case of exact matches.  Reversing order in this cases => lots of hits much higher than the one we're looking for:

![image](https://user-images.githubusercontent.com/112839/98539593-8528c080-2284-11eb-9e4f-53be5be0599d.png)

![image](https://user-images.githubusercontent.com/112839/98539432-3bd87100-2284-11eb-8345-8b97789237ee.png)

(Note images turned off)

**Comment by Robbie1977** [comment]
Fixed and released
