### ISSUE TITLE
Query links don't work - possibly because they trigger quickhelp

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB2#287]
e.g. 

https://v2.virtualflybrain.org/org.geppetto.frontend/org.geppetto.frontend?q=FBbt_00003932,ImagesNeurons

**Comment by dosumis** [comment]
Note - they also fail when QuickHelp has been blocked (by previously checking option to not show)

**Comment by Robbie1977** [comment]
link is wrong (the url shown by copying links did have this issue [missing /geppetto before? ]). All copied query links are now correct e.g. Images of neurons with some part in antennal lobe glomerulus DA1 https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?q=FBbt_00003932,ImagesNeurons
