### ISSUE TITLE
Neuron:Neuron Connectivity query results 

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB2#293]
Gross types incorrect -  look like they are for the parent class?

![image](https://user-images.githubusercontent.com/112839/102520353-89b67500-408b-11eb-8674-8f9618ba9acf.png)

![image](https://user-images.githubusercontent.com/112839/102520556-bc606d80-408b-11eb-946f-2203c85f4caa.png)

Support info:
Thu Dec 17 2020 17:15:52 GMT+0000 (Greenwich Mean Time)
Chrome
87.0.4280.88 [2486,1282]
https://debug.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_jrchk8br&i=VFB_00101567,VFB_00014123,VFB_jrchjtd6,VFB_jrchk10j

**Comment by dosumis** [comment]
Also note, parent class is duplicated in many cases.  Does this reflect underlying data (redundancy should be stripped)

**Comment by Robbie1977** [comment]
Gross types have been removed and duplicates from parent removed.
