### ISSUE TITLE
Tweak neuron:neuron connectivity headers

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB2#294]
![image](https://user-images.githubusercontent.com/112839/102521110-6d670800-408c-11eb-9a61-fdd0c55a464a.png)

Parent -> Type
Weight is unused - please drop.

Maybe drop T-bars column here too @admclachlan - do we include this for neuron:neuron?

More complete example:
![image](https://user-images.githubusercontent.com/112839/102581641-e13efa00-40f8-11eb-82db-9333b5a348c0.png)
Note sure imaging technique or template columns are useful here.  Presumably will always be same, so I think better to drop for simplicity.

**Comment by admclachlan** [comment]
Currently I'm only fetching neuron:neuron connectivity as pre>post weights. Probably could get T-bar counts with a custom neuprint query if that is useful.

**Comment by dosumis** [comment]
@Robbie1977  As T-bars not currently present in data, please drop
