### ISSUE TITLE
Is NBLAST Similar to not working?

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB2#303]
Please give details of the issue:

Example: VGlut-F-000517

Support info:
Mon Jan 18 2021 22:41:14 GMT+0000 (Greenwich Mean Time)
Chrome
87.0.4280.141 [2560,1439]
https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_00008878&i=VFB_00101567,VFB_jrchk4o7

**Comment by Robbie1977** [comment]
it was working but seems to have reverted back to master version so hurrying the PR merge on 'vfbr' package

**Comment by admclachlan** [comment]
fixed
