### ISSUE TITLE
Lee Lineages 2020 dataset broken?

### ISSUE THREAD

**Issue by j6k4m8** [VirtualFlyBrain/VFB2#313]
##### Description of the problem

Hey all — awesome project and great resource to the community!

The Lee Lineages 2020 dataset does not appear to load correctly when navigating to the project page (https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=Lee_Lineage2020) as listed in the manuscript (https://elifesciences.org/articles/53518#data). The JSON file that is requested by the page (https://virtualflybrain.org/data/VFB/json/Lee_Lineage2020.html) also 404s when I hit it manually in the browser.

Let me know if I can try troubleshooting anything for you on my end!

* Referring page: https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=Lee_Lineage2020
* System details: Firefox 93.0 [1087,953] Thu Nov 04 2021 14:02:47 GMT-0400 (Eastern Daylight Time)

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by j6k4m8** [comment]
Aha — looks like the key might be `Lee2020.html`?

**Comment by Robbie1977** [comment]
@j6k4m8 sorry about the delay and the error. You are correct this got assigned Lee2020 but will be corrected in the next release as the name in the paper was reserved for that dataset.

**Comment by Robbie1977** [comment]
https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=Lee2020

**Comment by j6k4m8** [comment]
Thank you so much for the update and links!!
