### ISSUE TITLE
Documentation/Hugo: Favicon doesn't display on firefox

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB2#321]
##### Description of the problem

Tested two machines. https://www.virtualflybrain.org/favicon.ico works on firefox and on that page the favicon does display in on the tab. Otherwise the hugo site doesn't get a favicon on firefox. The main site works fine though.

If others get this issue as well probably worth fixing.

This form is for VFB2 bug reports and feature requests.

If you need help, please use the [forum](https://groups.google.com/forum/#!forum/vfb-suport).

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant data to help us understand your issue.

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Robbie1977** [comment]
@admclachlan should be fixed on the next build. so if you can check when you're back this should be fixed

**Comment by admclachlan** [comment]
Confirmed fixed.
