### ISSUE TITLE
v2-dev json null issue

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB2#330]
Please give details of the issue:

Probably being fixed as on dev but many terms appear to be giving 'null' json results like this:

![Screenshot 2022-05-20 at 10 12 50](https://user-images.githubusercontent.com/56207505/169496010-d59f7e8c-650f-48a4-a839-96be085b74d9.png)

Support info:
Fri May 20 2022 10:11:39 GMT+0100 (British Summer Time)
Firefox
100.0 [2560,1490]
https://v2-dev.virtualflybrain.org/org.geppetto.frontend/geppetto?id=FBbt_00049111&i=VFB_00101567

**Comment by Robbie1977** [comment]
Was temp issue.
