### ISSUE TITLE
missing search results for split classes

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB2#339]
Please give details of the issue:

Searching for 'P{R95A10-GAL4.DBD} ∩ P{R24E06-p65.AD} expression pattern' finds the split class as expected

But 'P{R95A10-GAL4.DBD} ∩ P{R24E06-p65.AD}' or 'P{R95A10-GAL4.DBD} ∩ P{R24E06-p65.AD} expression' (or similar) does not. This appears to be the case with all split classes.

Tokenisation issue?

Support info:
Fri Sep 30 2022 16:32:10 GMT+0100 (British Summer Time)
Firefox
104.0 [1398,790]
https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFBexp_FBtp0099513FBtp0099531&i=VFB_00101567

**Comment by admclachlan** [comment]
The ∩ is also required which makes searching without copy/pasting difficult

**Comment by Robbie1977** [comment]
The curly brackets seem to be the issue (suspect they are being escaped incorrectly for solr)

**Comment by Robbie1977** [comment]
The query is getting trough OK but there is an issue with the solr tokenisation of the curly brackets as this should return the Splits:
https://solr.virtualflybrain.org/solr/ontology/select?json=%7B%22params%22:%7B%22q%22:%22P{R24E06-p65.AD+OR+P{R24E06-p65.AD*+OR+*P{R24E06-p65.AD*%22,%22defType%22:%22edismax%22,%22qf%22:%22label%5E100+synonym%5E100+label_autosuggest+synonym_autosuggest+shortform_autosuggest%22,%22indent%22:%22true%22,%22fl%22:%22short_form,label,synonym,id,facets_annotation,unique_facets%22,%22start%22:%220%22,%22pf%22:%22true%22,%22fq%22:[%22(short_form:VFB*+OR+short_form:FB*+OR+facets_annotation:DataSet+OR+facets_annotation:pub)+AND+NOT+short_form:VFBc_*%22],%22rows%22:%22100%22,%22wt%22:%22json%22,%22bq%22:%22short_form:VFBexp*%5E10.0+short_form:VFB*%5E100.0+short_form:FBbt*%5E100.0+short_form:FBbt_00003982%5E2+facets_annotation:Deprecated%5E0.001+facets_annotation:Split%5E100%22%7D%7D 


Ref https://sitecore.stackexchange.com/questions/31165/how-to-search-only-curly-braces-i-e-in-solr-search-using-solr-url

**Comment by Robbie1977** [comment]
Escaping the curly brackets i.e. search for ```P\{R24E06-p65.AD\}``` resolves the issue so a code change is being worked out now to fix resolve.

**Comment by admclachlan** [comment]
Thanks Robbie, I tried using escapes and found that it does work but the ∩ is still required. Does it make sense if users can find splits with just something like 'R24E06-p65.AD R95A10-GAL4.DBD'? Just '24E06 95A10' does work so it seems to me specifying the AD and DBD should also work.

**Comment by admclachlan** [comment]
Not including the ∩ ex 'P\{R95A10-GAL4.DBD\} P\{R24E06-p65.AD\}' can also give odd results like for this example it also returns 'P{R14A06-GAL4.DBD} ∩ P{R10B11-p65.AD} expression pattern'.

**Comment by admclachlan** [comment]
All examples here are fixed now confirmed on v2-dev. Matching with partial enhancer fragment names doesn't work but not sure it we actually want that so closing.
