### ISSUE TITLE
Fix FlyLight xref text

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB2#341]
Please give details of the issue:

[JRC_SS02111_Brain_2018_20141209_31_F1_20x on Driver Line on the FlyLight Split-GAL4 Site](http://splitgal4.janelia.org/cgi-bin/view_splitgal4_imagery.cgi?line=SS02111)

should be

[JRC_SS02111_Brain_2018_20141209_31_F1_20x Driver Line on the FlyLight Split-GAL4 Site](http://splitgal4.janelia.org/cgi-bin/view_splitgal4_imagery.cgi?line=SS02111)

same for the sample xrefs

Support info:
Mon Oct 31 2022 09:55:24 GMT+0000 (Greenwich Mean Time)
Firefox
105.0 [1398,790]
https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFBexp_FBtp0124959FBtp0120957&i=VFB_00101567,VFB_001012f0

**Comment by Robbie1977** [comment]
@admclachlan this one is tricky as the 'on' is added by the code rather than the site label so we either need to change the label to work or amend the code and update all site labels to work.
