### ISSUE TITLE
Issues in Safari

### ISSUE THREAD

**Issue by jdarmstrong** [VirtualFlyBrain/VFB2#355]
Please give details of the issue:

Support info:
Wed Apr 26 2023 13:42:01 GMT+0100 (British Summer Time)
Safari
16.2 [1961,475]
https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_00101567&i=VFB_00101567

[Log] THREE.WebGLRenderer – "87" (main.bundle.js, line 1)
[Log] Loading IDS to add to the scene from url (main.bundle.js, line 303)
[Log] Host for MessageSocket to connect: wss://v2.virtualflybrain.org/org.geppetto.frontend/GeppettoServlet (main.bundle.js, line 303)
[Log]  WebSocket Status - Opened  (main.bundle.js, line 303)
[Error] SyntaxError: JSON Parse error: Unterminated string
	parse (main.bundle.js:290:3263)
	l (main.bundle.js:290:3263)
	(anonymous function) (main.bundle.js:290:5126)
	(anonymous function) (main.bundle.js:290:5278)
[Error] WebSocket connection to 'wss://v2.virtualflybrain.org/org.geppetto.frontend/GeppettoServlet' failed: The operation couldn’t be completed. (kNWErrorDomainPOSIX error 100 - Protocol error)
[Log]  WebSocket Status - Open connection error  (main.bundle.js, line 303)
[Log] WebSocket Status - retry in 5000ms – CloseEvent (main.bundle.js, line 303)
CloseEvent
[Log]  WebSocket Status - reconnecting...  (main.bundle.js, line 303)
[Log]  WebSocket Status - Opened  (main.bundle.js, line 303)
> Selected Element
< <div class="flexChildContainer" style="position: fixed; height: 183px; width: 568px;">…</div>
[Warning] [blocked] The page at https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_00101567&i=VFB_00101567 was not allowed to run insecure content from http://gd.geobytes.com/GetCityDetails?callback=jQuery36109875237128015402_1682512888182&_=1682512888183. (common.bundle.js, line 25)

**Comment by Robbie1977** [comment]
This issue was resolved in latest releases
