### ISSUE TITLE
Links in term info don't work 

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB2#38]
https://v2-dev.virtualflybrain.org/?i=VFB_00017894

Clicking on any of the links under 'Type' doesn't do anything. Should it?
Clicking on the anatomy terms under Relationships' also doesn't do anything. Should it? For example, the first time I click on 'lateral horn' nothing happens (I assumed I would see the info for that term). Second click goes to 
<img width="752" alt="screen shot 2018-03-12 at 22 31 49" src="https://user-images.githubusercontent.com/1872083/37313008-3c36b0c8-2645-11e8-90a9-c8e4328f7564.png">

This is quite annoying because the history is then lost, and going back on the browser shows the homepage, template only, no terms selected or added.

Support info:
Referring page: https://v2-dev.virtualflybrain.org/?i=VFB_00017894
System details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36 Size:[1280,676]

**Comment by Robbie1977** [comment]
Should be resolved

**Comment by mmc46** [comment]
Working now, thanks.
