### ISSUE TITLE
Slice indicator unresponsive

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB2#39]
Template + medulla.
Clicking on the slice indicator in the slice viewer doesn't do anything. 
Only after moving the slice viewer widget to the left, does it work. After turning it on, and moving the widget back to the right, the button becomes unresponsive again. Moving the widget back to the left, and it works.

Support info:
Referring page: https://v2-dev.virtualflybrain.org/?i=VFB_00017894,VFB_00030624
System details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36 Size:[1280,676]

**Comment by Robbie1977** [comment]
Please retest

**Comment by mmc46** [comment]
Working now, thanks.
