### ISSUE TITLE
Cosmetic improvements

### ISSUE THREAD

**Issue by tarelli** [VirtualFlyBrain/VFB2#7]
1. ![screen shot 2017-05-24 at 11 36 07](https://cloud.githubusercontent.com/assets/81127/26401622/a206eb00-407e-11e7-8466-0130cba8e77f.png)
2. ![screen shot 2017-05-24 at 11 27 20](https://cloud.githubusercontent.com/assets/81127/26401619/a1fa8108-407e-11e7-92d6-1192e038b60c.png)
3. ![screen shot 2017-05-24 at 11 27 05](https://cloud.githubusercontent.com/assets/81127/26401620/a1fb0524-407e-11e7-999d-d2bc15391cb6.png)
4. ![screen shot 2017-05-24 at 11 27 14](https://cloud.githubusercontent.com/assets/81127/26401621/a1ffa7b4-407e-11e7-820a-93ecbe5daebd.png)
5. ![screen shot 2017-05-24 at 11 26 46](https://cloud.githubusercontent.com/assets/81127/26401791/794ee4dc-407f-11e7-98ff-df23b98fd5d1.png)
6. ![screen shot 2017-05-24 at 11 26 56](https://cloud.githubusercontent.com/assets/81127/26401792/794f003e-407f-11e7-9ece-4dc2290c36ba.png)

**Comment by tarelli** [comment]
1. Suggestion for an alternative quasi neutral color, too much orange makes it not too easy on the eye. Also made the font bigger instead of bold and used font-weight:100 to make it a bit more gentle
1. I would replace the coloured social media icons with font-awesome ones and align the properly
2. The box is too big goes out of the screen, I'd resize the video and make it fit
3. Icons are too big compared to the text
3. For all the buttons there should be a slightly different colour (brighter) on hover
3. Maybe add a bit of transparency to the background
3. Not intuitive how to close it, maybe add an X?
4. Nothing has rounded corner, this dialog should not be different, I'd recommend keep same stile as the widgets

**Comment by Robbie1977** [comment]
Done as part of update
